spring:
  config:
    activate:
      on-profile: dev

today:
  message: helloworld-dev-안녕하세요.똠펲됬.11111111===
  date: 20240422
nexcore:
  database:
    charset: UTF-8

---
spring:
  config:
    activate:
      on-profile: prod

today:
  message: prod-운영안녕.리프레시.123456789
  date: 20240444

nexcore:
  database:
    charset: MS949


---
spring:
  config:
    activate:
      on-profile: k8s

today:
  message: k8s 안녕.1111
  date: 20240416

nexcore:
  database:
    charset: MS949




